FROM node:alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/worker-dns ./apps/worker-dns
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile

RUN pnpm run db:generate
RUN pnpm build


CMD [ "pnpm", "run", "start:worker-dns" ]