FROM node:alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/worker-alert ./apps/worker-alert

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile

CMD [ "pnpm", "run", "start:worker-alert" ]