FROM node:alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/frontend ./apps/frontend

RUN cd apps/frontend
#this step can be replaced by just pnpm install, if pnpm is installed in vm
RUN npm install -g pnpm
RUN pnpm install 

EXPOSE 8080

CMD [ "pnpm", "run", "start:frontend" ]
