FROM node:20-bullseye-slim

WORKDIR /usr/src/app

COPY ./packages ./packages
#will have packages version as in the real one and versions won't conflict
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml  

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/api ./apps/api

RUN npm install -g pnpm 
RUN pnpm install --frozen-lockfile

RUN apt-get update && apt-get install -y openssl

RUN pnpm run db:generate -- --debug


EXPOSE 3001

CMD [ "pnpm", "run", "start:api" ]